image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - deploy

maven-build:
  image: maven:3.8.4-openjdk-8
  stage: build
  script:
    - mvn package -B
  artifacts:
    paths:
      - ./banque.jar

docker-build:
  stage: deploy
  script:
    - docker build -t mohammedbouqs/spring-bonjourapp .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push mohammedbouqs/spring-bonjourapp
